### ISSUE TITLE
`resolve_opaque_op` fails when `OpaqueOp` does not explicitly require it's own extension.

### ISSUE THREAD

**Issue by doug-q** [Quantinuum/hugr#1315]
Perhaps `OpaqueOp`s extension should get added to it's signature before the comparison?

**Comment by acl-cqc** [comment]
See also https://github.com/CQCL/hugr/issues/1209. However your suggestion is a less "dangerous" sounding fix for any regression caused by #1226 and if resolve_opaque_op isn't causing trouble with other extension mismatches then it might well make sense to do that. (IOW it's a "backwards compatibility fix" for Hugrs serialized before #1226)
